// SPDX-License-Identifier: AGPL-3.0-or-later

// GET /api/documents/{id}/thumb/ — serves the first-page thumbnail
// generated by the post-ingest pipeline (core/pipeline/thumb). PNG,
// ETag = documents.thumb_sha with private revalidation on every use.
//
// 404 for docs without thumb_sha (non-PDFs, documents ingested without
// pdftoppm, or older docs pre-migration). The
// SPA falls back to its title-initials placeholder.
//
// ACL: same rule as GET /api/documents/{id} (owner or ACL grant).
//
// Sensitivity gate: mirrors the /preview/{id} handler. Confidential
// and restricted docs return 202 with a small JSON body unless the
// caller explicitly opts in with ?reveal=1. Keeps direct URL access
// (e.g. an audit or a stray bookmark scan) from surfacing the raw
// first page while the SPA still requests the pixels with reveal=1
// on behalf of the authorized user viewing the list.

package api

import (
	"bytes"
	"database/sql"
	"errors"
	"image"
	"image/png"
	"io"
	"net/http"
	"strconv"

	"github.com/johnnybravo-xyz/suchi/core/auth"
	"github.com/johnnybravo-xyz/suchi/core/authz"
	"github.com/johnnybravo-xyz/suchi/core/blob"
	xdraw "golang.org/x/image/draw"
)

// GetDocumentThumb serves the doc's page-1 thumbnail.
func (s *Server) GetDocumentThumb(w http.ResponseWriter, r *http.Request) {
	if !auth.RequireScope(w, r, auth.ScopeDocumentsRead) {
		return
	}
	p := auth.FromContext(r.Context())
	id, err := parseIDPath(r)
	if err != nil {
		s.writeError(w, http.StatusBadRequest, "bad_id", err.Error())
		return
	}
	requestedWidth, resize, err := parseThumbnailWidth(r)
	if err != nil {
		s.writeError(w, http.StatusBadRequest, "bad_width", "width must be one integer from 64 through 512")
		return
	}
	if !s.authorize(w, r, p, authz.KindDocument, id, authz.PermView) {
		return
	}
	var (
		sha  sql.NullString
		sens sql.NullString
	)
	err = s.DB.Read.QueryRowContext(r.Context(),
		`SELECT thumb_sha, sensitivity FROM documents WHERE id = ? AND trashed_at IS NULL`,
		id).Scan(&sha, &sens)
	if errors.Is(err, sql.ErrNoRows) {
		s.writeError(w, http.StatusNotFound, "not_found", "document not found")
		return
	}
	if err != nil {
		s.serverErr(w, "thumb.load", err)
		return
	}
	if sens.Valid && IsHighSensitivity(sens.String) &&
		r.URL.Query().Get("reveal") != "1" {
		revealURL := "?reveal=1"
		if resize {
			revealURL += "&width=" + strconv.Itoa(requestedWidth)
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("X-Sensitivity", sens.String)
		// Never cache the gate response so a later reclassification
		// (or a later reveal) isn't masked by a stale 202.
		w.Header().Set("Cache-Control", "no-store")
		w.WriteHeader(http.StatusAccepted)
		_, _ = w.Write([]byte(
			`{"sensitivity":"` + sens.String + `",` +
				`"gated":true,"reveal_url":"` + revealURL + `"}`))
		return
	}
	if !sha.Valid || sha.String == "" {
		s.writeError(w, http.StatusNotFound, "no_thumb", "no thumbnail for this document")
		return
	}
	if !resize {
		etag := `"` + sha.String + `"`
		w.Header().Set("ETag", etag)
		w.Header().Set("Cache-Control", "private, no-cache")
		if match := r.Header.Get("If-None-Match"); match != "" && match == etag {
			w.WriteHeader(http.StatusNotModified)
			return
		}
		rc, err := s.CAS.GetContext(r.Context(), sha.String)
		if errors.Is(err, blob.ErrNotFound) {
			s.writeError(w, http.StatusNotFound, "no_thumb", "thumbnail blob missing")
			return
		}
		if err != nil {
			s.serverErr(w, "thumb.get", err)
			return
		}
		defer rc.Close()
		w.Header().Set("Content-Type", "image/png")
		if _, err := io.Copy(w, rc); err != nil {
			s.Log.Warn("thumb.copy", "err", err.Error())
		}
		return
	}

	rc, err := s.CAS.GetContext(r.Context(), sha.String)
	if errors.Is(err, blob.ErrNotFound) {
		s.writeError(w, http.StatusNotFound, "no_thumb", "thumbnail blob missing")
		return
	}
	if err != nil {
		s.serverErr(w, "thumb.get", err)
		return
	}
	sourceBytes, err := io.ReadAll(rc)
	rc.Close()
	if err != nil {
		s.serverErr(w, "thumb.read", err)
		return
	}
	config, err := png.DecodeConfig(bytes.NewReader(sourceBytes))
	if err != nil {
		s.serverErr(w, "thumb.decode", err)
		return
	}
	sourceWidth := config.Width
	sourceHeight := config.Height
	if sourceWidth <= 0 || sourceHeight <= 0 {
		s.writeError(w, http.StatusInternalServerError, "thumb_decode", "stored thumbnail has invalid dimensions")
		return
	}
	actualWidth := min(requestedWidth, sourceWidth)
	etag := `"` + sha.String + `-w` + strconv.Itoa(actualWidth) + `"`
	if match := r.Header.Get("If-None-Match"); match != "" && match == etag {
		w.Header().Set("ETag", etag)
		w.Header().Set("Cache-Control", "private, no-cache")
		w.WriteHeader(http.StatusNotModified)
		return
	}
	output := sourceBytes
	if actualWidth < sourceWidth {
		source, err := png.Decode(bytes.NewReader(sourceBytes))
		if err != nil {
			s.serverErr(w, "thumb.decode", err)
			return
		}
		targetHeight := max(1, (sourceHeight*actualWidth+sourceWidth/2)/sourceWidth)
		target := image.NewRGBA(image.Rect(0, 0, actualWidth, targetHeight))
		xdraw.CatmullRom.Scale(target, target.Bounds(), source, source.Bounds(), xdraw.Over, nil)
		var encoded bytes.Buffer
		if err := png.Encode(&encoded, target); err != nil {
			s.serverErr(w, "thumb.encode", err)
			return
		}
		output = encoded.Bytes()
	}
	w.Header().Set("ETag", etag)
	w.Header().Set("Cache-Control", "private, no-cache")
	w.Header().Set("Content-Type", "image/png")
	if _, err := w.Write(output); err != nil {
		s.Log.Warn("thumb.copy", "err", err.Error())
	}
}

func parseThumbnailWidth(r *http.Request) (width int, present bool, err error) {
	values, present := r.URL.Query()["width"]
	if !present {
		return 0, false, nil
	}
	if len(values) != 1 {
		return 0, true, errors.New("duplicate width")
	}
	width, err = strconv.Atoi(values[0])
	if err != nil || width < 64 || width > 512 {
		return 0, true, errors.New("invalid width")
	}
	return width, true, nil
}
